### ISSUE TITLE
Refactor Tuva Claims Demo

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/the_tuva_project_demo#10]
- Tuva Claims Demo is currently not working.  We need it working with the refactor.

Aaron's thoughts:

- It should include 3 models named after the input layer so the tuva package refs will work.

**Comment by aneiderhiser** [comment]
@cocozuloaga I created this so we wouldn't use track of this w/ the refactor.  @tuvaforrest add this to your list (assuming coco doesn't get to it first).

**Comment by sarahmcmorgan** [comment]
Updated tasks:

- [ ] Clean up dbt_project.yml, remove unnecessary vars
- [ ] Install the package-consolidation branch from the Tuva Project repo and test the new package
- [ ] Update the package version for the Tuva Project to the latest version (0.3.0)
