### ISSUE TITLE
Update Tuva Claims Demo Tutorial

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/the_tuva_project_demo#14]
Here's how the quickstart tutorial should work:

1. Clone tuva_claims_demo from Github
2. Configure the dbt project to run in your environment
3. Import the_tuva_project package
4. Run `dbt build`.  Describe how this loads a synthetic claims dataset into your data warehouse from S3 and builds the entire Tuva Project
5. Setup and run tuva_analytics

**Comment by aneiderhiser** [comment]
@tuvaforrest need you to update the functionality to load full dataset from s3.

**Comment by aneiderhiser** [comment]
@thutuva and @cocozuloaga - i know we need forrest to do NDC as well.  but currently tuva_claims_demo only works on 50 patient sample.  we need the larger sample for dbt partnership demos.

@tuvaforrest how long would this take (just talking loading from s3)?  maybe if it's not too bad we can do this before NDC?

**Comment by aneiderhiser** [comment]
@aneiderhiser test

**Comment by sarahmcmorgan** [comment]
@aneiderhiser @tuvaforrest S3 seed logic was added with PR https://github.com/tuva-health/tuva_claims_demo/pull/17.
