### ISSUE TITLE
Admission and Discharge Dates

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/the_tuva_project_demo#19]
Both admission_date and discharge_date are always null.  We need admission and discharge dates for inpatient analytics.  An easy option might be to use claim_start_date and claim_end_date for any claim_id that has a DRG.  We want to make sure that length of stay, which equals discharge - admit, produces a reasonable average.  This number should be between 3 and 6 days probably.

**Comment by sarahmcmorgan** [comment]
@aneiderhiser Thu Xuan resolved this issue back in June. The synthetic claims data now has admission and discharge dates. Do we still need to keep this open?

**Comment by aneiderhiser** [comment]
Nope - I'll close it.
