### ISSUE TITLE
dispatch in dbt_project.yml wrong

### ISSUE THREAD

**Issue by thuxuan-vu** [tuva-health/the_tuva_project_demo#2]
The `dispatch` variable/function (not sure what to call it) does not work as intended because the 'search order' part is wrong.  Instead of 'the_tuva_project' it needs to be the current project's name so it should be 'tuva_claims_demo'.

I changed this locally and confirmed that the issue was fixed.  The schemas being generated were no longer prefixed with the target schema.

**Comment by aneiderhiser** [comment]
@thutuva @cocozuloaga i'm guessing we can close this issue because we won't use this functionality in the refactored packages?

**Comment by thuxuan-vu** [comment]
@aneiderhiser yea we can close it.  I'll take care of that.

**Comment by sarahmcmorgan** [comment]
@aneiderhiser @cocozuloaga @thutuva Yes, this bug was already corrected. Sorry, the issue had not been resolved yet.
